// src/lib/textmetrics.ts
// How wide is this string — with no DOM, in Node and in the browser, giving the same answer in both.
//
// The poster is built by a pure string builder (render.ts) that runs at build time under Astro and again
// in the browser for a typed city, and the centre block cannot be laid out without knowing how wide its
// lines are. Nothing in that path can measure text: Node has no canvas, and the build has no document.
// So the three faces the poster sets are carried here as per-character advance tables in em fractions,
// measured once from the real webfonts and committed.
//
// GENERATED by scripts/textmetrics.mjs — do not hand-edit. Regenerate only if the fonts change.
//
// Sum-of-advances ignores kerning, which is the safe direction — Plex's kerning is almost entirely
// negative, so the estimate runs slightly WIDE and the fitter shrinks a hair more than it had to.
// Validated against the browser's own SVG getComputedTextLength() over 81 real strings (every curated
// city name, signature and country at its real letter-spacing, plus a stress list):
//
//     min -0.91%   max +2.06%   mean |error| 0.345%
//
// SAFETY (below) covers the worst under-read with more than double the margin, and the generator refuses
// to write a table that would need more.
//
// TRAP: these come from canvas measureText, never from SVG getComputedTextLength. A <text> node whose
// content is a single " " collapses to ZERO width under XML whitespace rules, which silently zeroes the
// space advance and pushes the error to -7.5% on every multi-word string — i.e. exactly the long city
// names this table exists to catch.

export type Face = 'serif500' | 'sans400' | 'sans600';

type Advances = Record<string, number>;

/**
 * Latin-1 and below is IBM Plex itself. The Latin Extended-A block below is NOT in the `latin` webfont
 * subset the site loads, so those advances are the fallback face's (Georgia/Times) — correct, because the
 * fallback is what actually paints them, but platform-dependent. Rare enough in city names that SAFETY
 * plus the fitter's shrink -> wrap -> truncate ladder is the guard rather than a wider table.
 */
const SERIF_500: Advances = {
  '0': 0.6, '1': 0.6, '2': 0.6, '3': 0.6, '4': 0.6, '5': 0.6,
  '6': 0.6, '7': 0.6, '8': 0.6, '9': 0.6, ' ': 0.232, '!': 0.292,
  '"': 0.444, '#': 0.671, '$': 0.593, '%': 0.919, '&': 0.726, '\'': 0.249,
  '(': 0.336, ')': 0.336, '*': 0.506, '+': 0.6, ',': 0.272, '-': 0.396,
  '.': 0.272, '/': 0.392, ':': 0.292, ';': 0.293, '<': 0.6, '=': 0.6,
  '>': 0.6, '?': 0.501, '@': 0.914, 'A': 0.692, 'B': 0.685, 'C': 0.656,
  'D': 0.728, 'E': 0.649, 'F': 0.632, 'G': 0.744, 'H': 0.799, 'I': 0.363,
  'J': 0.481, 'K': 0.735, 'L': 0.606, 'M': 0.882, 'N': 0.784, 'O': 0.736,
  'P': 0.65, 'Q': 0.736, 'R': 0.699, 'S': 0.605, 'T': 0.677, 'U': 0.75,
  'V': 0.677, 'W': 0.993, 'X': 0.694, 'Y': 0.655, 'Z': 0.644, '[': 0.309,
  '\\': 0.392, ']': 0.309, '^': 0.6, '_': 0.563, '`': 0.6, 'a': 0.553,
  'b': 0.609, 'c': 0.524, 'd': 0.619, 'e': 0.547, 'f': 0.36, 'g': 0.56,
  'h': 0.635, 'i': 0.323, 'j': 0.311, 'k': 0.597, 'l': 0.31, 'm': 0.958,
  'n': 0.648, 'o': 0.572, 'p': 0.622, 'q': 0.61, 'r': 0.464, 's': 0.497,
  't': 0.361, 'u': 0.631, 'v': 0.549, 'w': 0.817, 'x': 0.574, 'y': 0.55,
  'z': 0.511, '{': 0.349, '|': 0.332, '}': 0.349, '~': 0.6, '\u00b0': 0.468,
  '\u00b7': 0.334, '\u2013': 0.589, '\u2014': 0.785, '\u2018': 0.272, '\u2019': 0.272, '\u201c': 0.489,
  '\u201d': 0.489, '\u2026': 0.816, '\u00c0': 0.692, '\u00c1': 0.692, '\u00c2': 0.692, '\u00c3': 0.692,
  '\u00c4': 0.692, '\u00c5': 0.692, '\u00c6': 0.982, '\u00c7': 0.656, '\u00c8': 0.649, '\u00c9': 0.649,
  '\u00ca': 0.649, '\u00cb': 0.649, '\u00cc': 0.363, '\u00cd': 0.363, '\u00ce': 0.363, '\u00cf': 0.363,
  '\u00d1': 0.784, '\u00d2': 0.736, '\u00d3': 0.736, '\u00d4': 0.736, '\u00d5': 0.736, '\u00d6': 0.736,
  '\u00d8': 0.736, '\u00d9': 0.75, '\u00da': 0.75, '\u00db': 0.75, '\u00dc': 0.75, '\u00dd': 0.655,
  '\u00df': 0.674, '\u00e0': 0.553, '\u00e1': 0.553, '\u00e2': 0.553, '\u00e3': 0.553, '\u00e4': 0.553,
  '\u00e5': 0.553, '\u00e6': 0.831, '\u00e7': 0.524, '\u00e8': 0.547, '\u00e9': 0.547, '\u00ea': 0.547,
  '\u00eb': 0.547, '\u00ec': 0.323, '\u00ed': 0.323, '\u00ee': 0.323, '\u00ef': 0.323, '\u00f1': 0.648,
  '\u00f2': 0.572, '\u00f3': 0.572, '\u00f4': 0.572, '\u00f5': 0.572, '\u00f6': 0.572, '\u00f8': 0.572,
  '\u00f9': 0.631, '\u00fa': 0.631, '\u00fb': 0.631, '\u00fc': 0.631, '\u00fd': 0.55, '\u00ff': 0.55,
  '\u0100': 0.7222, '\u0101': 0.4438, '\u010c': 0.667, '\u010d': 0.4438, '\u0110': 0.7222, '\u0111': 0.5,
  '\u011e': 0.7222, '\u011f': 0.5, '\u0130': 0.333, '\u0131': 0.323, '\u0141': 0.6108, '\u0142': 0.2778,
  '\u0152': 1.027, '\u0153': 0.915, '\u015e': 0.5562, '\u015f': 0.3892, '\u0160': 0.5562, '\u0161': 0.3892,
  '\u016a': 0.7222, '\u016b': 0.5, '\u017d': 0.6108, '\u017e': 0.4438,
};

const SANS_400: Advances = {
  '0': 0.6, '1': 0.6, '2': 0.6, '3': 0.6, '4': 0.6, '5': 0.6,
  '6': 0.6, '7': 0.6, '8': 0.6, '9': 0.6, ' ': 0.236, '!': 0.284,
  '"': 0.419, '#': 0.713, '$': 0.598, '%': 0.927, '&': 0.694, '\'': 0.242,
  '(': 0.335, ')': 0.335, '*': 0.45, '+': 0.6, ',': 0.272, '-': 0.399,
  '.': 0.272, '/': 0.383, ':': 0.292, ';': 0.292, '<': 0.6, '=': 0.6,
  '>': 0.6, '?': 0.477, '@': 0.891, 'A': 0.641, 'B': 0.653, 'C': 0.621,
  'D': 0.671, 'E': 0.583, 'F': 0.559, 'G': 0.695, 'H': 0.707, 'I': 0.4,
  'J': 0.51, 'K': 0.634, 'L': 0.501, 'M': 0.812, 'N': 0.707, 'O': 0.708,
  'P': 0.606, 'Q': 0.708, 'R': 0.64, 'S': 0.581, 'T': 0.572, 'U': 0.678,
  'V': 0.609, 'W': 0.891, 'X': 0.613, 'Y': 0.593, 'Z': 0.58, '[': 0.317,
  '\\': 0.383, ']': 0.317, '^': 0.6, '_': 0.565, '`': 0.6, 'a': 0.534,
  'b': 0.58, 'c': 0.503, 'd': 0.58, 'e': 0.549, 'f': 0.324, 'g': 0.528,
  'h': 0.568, 'i': 0.25, 'j': 0.25, 'k': 0.527, 'l': 0.272, 'm': 0.873,
  'n': 0.568, 'o': 0.56, 'p': 0.58, 'q': 0.58, 'r': 0.367, 's': 0.487,
  't': 0.351, 'u': 0.568, 'v': 0.492, 'w': 0.768, 'x': 0.507, 'y': 0.499,
  'z': 0.464, '{': 0.343, '|': 0.314, '}': 0.343, '~': 0.6, '\u00b0': 0.468,
  '\u00b7': 0.326, '\u2013': 0.588, '\u2014': 0.78, '\u2018': 0.273, '\u2019': 0.273, '\u201c': 0.475,
  '\u201d': 0.474, '\u2026': 0.803, '\u00c0': 0.641, '\u00c1': 0.641, '\u00c2': 0.641, '\u00c3': 0.641,
  '\u00c4': 0.641, '\u00c5': 0.641, '\u00c6': 0.907, '\u00c7': 0.621, '\u00c8': 0.583, '\u00c9': 0.583,
  '\u00ca': 0.583, '\u00cb': 0.583, '\u00cc': 0.4, '\u00cd': 0.4, '\u00ce': 0.4, '\u00cf': 0.4,
  '\u00d1': 0.707, '\u00d2': 0.708, '\u00d3': 0.708, '\u00d4': 0.708, '\u00d5': 0.708, '\u00d6': 0.708,
  '\u00d8': 0.708, '\u00d9': 0.678, '\u00da': 0.678, '\u00db': 0.678, '\u00dc': 0.678, '\u00dd': 0.593,
  '\u00df': 0.64, '\u00e0': 0.534, '\u00e1': 0.534, '\u00e2': 0.534, '\u00e3': 0.534, '\u00e4': 0.534,
  '\u00e5': 0.534, '\u00e6': 0.864, '\u00e7': 0.503, '\u00e8': 0.549, '\u00e9': 0.549, '\u00ea': 0.549,
  '\u00eb': 0.549, '\u00ec': 0.25, '\u00ed': 0.25, '\u00ee': 0.25, '\u00ef': 0.25, '\u00f1': 0.568,
  '\u00f2': 0.56, '\u00f3': 0.56, '\u00f4': 0.56, '\u00f5': 0.56, '\u00f6': 0.56, '\u00f8': 0.568,
  '\u00f9': 0.568, '\u00fa': 0.568, '\u00fb': 0.568, '\u00fc': 0.568, '\u00fd': 0.499, '\u00ff': 0.499,
  '\u0100': 0.7222, '\u0101': 0.4438, '\u010c': 0.667, '\u010d': 0.4438, '\u0110': 0.7222, '\u0111': 0.5,
  '\u011e': 0.7222, '\u011f': 0.5, '\u0130': 0.333, '\u0131': 0.25, '\u0141': 0.6108, '\u0142': 0.2778,
  '\u0152': 0.985, '\u0153': 0.931, '\u015e': 0.5562, '\u015f': 0.3892, '\u0160': 0.5562, '\u0161': 0.3892,
  '\u016a': 0.7222, '\u016b': 0.5, '\u017d': 0.6108, '\u017e': 0.4438,
};

const SANS_600: Advances = {
  '0': 0.6, '1': 0.6, '2': 0.6, '3': 0.6, '4': 0.6, '5': 0.6,
  '6': 0.6, '7': 0.6, '8': 0.6, '9': 0.6, ' ': 0.236, '!': 0.309,
  '"': 0.471, '#': 0.656, '$': 0.6, '%': 0.96, '&': 0.713, '\'': 0.26,
  '(': 0.337, ')': 0.337, '*': 0.556, '+': 0.6, ',': 0.299, '-': 0.402,
  '.': 0.299, '/': 0.437, ':': 0.319, ';': 0.319, '<': 0.6, '=': 0.6,
  '>': 0.6, '?': 0.493, '@': 0.899, 'A': 0.672, 'B': 0.663, 'C': 0.642,
  'D': 0.689, 'E': 0.6, 'F': 0.577, 'G': 0.712, 'H': 0.719, 'I': 0.423,
  'J': 0.545, 'K': 0.678, 'L': 0.521, 'M': 0.817, 'N': 0.719, 'O': 0.712,
  'P': 0.641, 'Q': 0.712, 'R': 0.664, 'S': 0.611, 'T': 0.58, 'U': 0.689,
  'V': 0.638, 'W': 0.949, 'X': 0.655, 'Y': 0.632, 'Z': 0.599, '[': 0.329,
  '\\': 0.437, ']': 0.329, '^': 0.6, '_': 0.559, '`': 0.6, 'a': 0.559,
  'b': 0.6, 'c': 0.513, 'd': 0.6, 'e': 0.558, 'f': 0.35, 'g': 0.545,
  'h': 0.588, 'i': 0.275, 'j': 0.275, 'k': 0.562, 'l': 0.294, 'm': 0.888,
  'n': 0.588, 'o': 0.563, 'p': 0.6, 'q': 0.6, 'r': 0.393, 's': 0.499,
  't': 0.374, 'u': 0.588, 'v': 0.524, 'w': 0.819, 'x': 0.544, 'y': 0.524,
  'z': 0.502, '{': 0.363, '|': 0.376, '}': 0.363, '~': 0.6, '\u00b0': 0.469,
  '\u00b7': 0.349, '\u2013': 0.588, '\u2014': 0.78, '\u2018': 0.292, '\u2019': 0.292, '\u201c': 0.517,
  '\u201d': 0.517, '\u2026': 0.869, '\u00c0': 0.672, '\u00c1': 0.672, '\u00c2': 0.672, '\u00c3': 0.672,
  '\u00c4': 0.672, '\u00c5': 0.672, '\u00c6': 0.95, '\u00c7': 0.642, '\u00c8': 0.6, '\u00c9': 0.6,
  '\u00ca': 0.6, '\u00cb': 0.6, '\u00cc': 0.423, '\u00cd': 0.423, '\u00ce': 0.423, '\u00cf': 0.423,
  '\u00d1': 0.719, '\u00d2': 0.712, '\u00d3': 0.712, '\u00d4': 0.712, '\u00d5': 0.712, '\u00d6': 0.712,
  '\u00d8': 0.712, '\u00d9': 0.689, '\u00da': 0.689, '\u00db': 0.689, '\u00dc': 0.689, '\u00dd': 0.632,
  '\u00df': 0.677, '\u00e0': 0.559, '\u00e1': 0.559, '\u00e2': 0.559, '\u00e3': 0.559, '\u00e4': 0.559,
  '\u00e5': 0.559, '\u00e6': 0.864, '\u00e7': 0.513, '\u00e8': 0.558, '\u00e9': 0.558, '\u00ea': 0.558,
  '\u00eb': 0.558, '\u00ec': 0.275, '\u00ed': 0.275, '\u00ee': 0.275, '\u00ef': 0.275, '\u00f1': 0.588,
  '\u00f2': 0.563, '\u00f3': 0.563, '\u00f4': 0.563, '\u00f5': 0.563, '\u00f6': 0.563, '\u00f8': 0.571,
  '\u00f9': 0.588, '\u00fa': 0.588, '\u00fb': 0.588, '\u00fc': 0.588, '\u00fd': 0.524, '\u00ff': 0.524,
  '\u0100': 0.7222, '\u0101': 0.5, '\u010c': 0.7222, '\u010d': 0.4438, '\u0110': 0.7222, '\u0111': 0.5562,
  '\u011e': 0.7778, '\u011f': 0.5, '\u0130': 0.3892, '\u0131': 0.275, '\u0141': 0.667, '\u0142': 0.2778,
  '\u0152': 0.994, '\u0153': 0.91, '\u015e': 0.5562, '\u015f': 0.3892, '\u0160': 0.5562, '\u0161': 0.3892,
  '\u016a': 0.7222, '\u016b': 0.5562, '\u017d': 0.667, '\u017e': 0.4438,
};

const FACES: Record<Face, Advances> = { serif500: SERIF_500, sans400: SANS_400, sans600: SANS_600 };

/** An unmeasured character is assumed full-em — a CJK-width over-read, so an exotic name shrinks rather than spills. */
export const UNKNOWN_ADVANCE = 1;

/** Applied to every width before it meets a budget. Covers the -0.91% worst-case under-read twice over. */
export const SAFETY = 1.02;

/**
 * Advance width of `text` in user units. `letterSpacing` is a fixed length the way SVG/CSS applies it —
 * after every character including the last, which is what Chrome measures and what the poster emits.
 */
export function advanceWidth(face: Face, text: string, fontSize: number, letterSpacing = 0): number {
  const table = FACES[face];
  let em = 0;
  for (const ch of text) em += table[ch] ?? UNKNOWN_ADVANCE;
  return em * fontSize + letterSpacing * [...text].length;
}

/** advanceWidth with the safety factor already applied. This is the one the fitter compares to a budget. */
export function fitWidth(face: Face, text: string, fontSize: number, letterSpacing = 0): number {
  return advanceWidth(face, text, fontSize, letterSpacing) * SAFETY;
}
